import { useMemo, useState } from "react";
import { Bot, CheckCircle2, ClipboardCheck, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

const audienceLabel: Record<string, string> = { admin: "Administração", partner: "Parceiro", consumer: "Consumidor", publisher: "Divulgador", internal: "Interno" };
const statusLabel: Record<string, string> = { draft: "Rascunho", active: "Ativo", paused: "Pausado", retired: "Retirado" };

export default function Agents() {
  const agents = trpc.admin.agents.list.useQuery();
  const [selectedKey, setSelectedKey] = useState("backoffice-operations");
  const [form, setForm] = useState({ agentKey: "backoffice-operations", name: "Operações do Backoffice", audience: "admin", status: "active", autonomy: "A1", policyVersion: "policy-v1.0", promptVersion: "prompt-v1.0" });
  const [runForm, setRunForm] = useState({ intent: "consultar_cupom", idempotencyKey: "agent-demo-0001", requesterReference: "operacao-demo", input: '{"couponId": 1}' });
  const createAgent = trpc.admin.agents.create.useMutation({ onSuccess: async () => { await agents.refetch(); toast.success("Perfil de agente criado"); }, onError: error => toast.error(error.message) });
  const planRun = trpc.admin.agents.plan.useMutation({ onSuccess: result => toast.success(result.route.approvalRequired ? "Execução registrada aguardando aprovação" : "Execução planejada"), onError: error => toast.error(error.message) });
  const activeAgent = useMemo(() => (agents.data ?? []).find(item => item.agentKey === selectedKey), [agents.data, selectedKey]);

  function submitAgent(event: React.FormEvent) { event.preventDefault(); createAgent.mutate({ ...form, entityId: null, partnerId: null, storeId: null } as never); }
  function submitRun(event: React.FormEvent) { event.preventDefault(); let input: Record<string, unknown>; try { input = JSON.parse(runForm.input) as Record<string, unknown>; } catch { toast.error("Entrada precisa ser um JSON válido"); return; } planRun.mutate({ agentKey: selectedKey, intent: runForm.intent, idempotencyKey: runForm.idempotencyKey, requesterReference: runForm.requesterReference, riskLevel: "low", input, status: "planned" }); }

  return <main className="space-y-6 p-6 md:p-8">
    <section className="rounded-3xl bg-[#101418] p-7 text-white md:p-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl space-y-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-[#f4c400]"><Bot className="size-4" /> Governança de agentes</div><h1 className="text-3xl font-semibold tracking-tight md:text-4xl">Autonomia com controle, evidência e escopo.</h1><p className="text-sm leading-6 text-white/65">Cadastre perfis, defina versões de política e planeje execuções. Ações de alto risco ficam aguardando aprovação humana.</p></div><Badge className="w-fit border-0 bg-[#f4c400] text-[#101418]">Modo supervisionado</Badge></div></section>

    <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
      <Card className="border-black/5 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-5 text-[#b58b00]" /> Perfis cadastrados</CardTitle><CardDescription>O perfil define público, escopo e autonomia máxima. A política determinística continua sendo a fonte de autorização.</CardDescription></CardHeader><CardContent className="space-y-3">{agents.isLoading ? <p className="text-sm text-muted-foreground">Carregando agentes…</p> : agents.data?.length ? agents.data.map(agent => <button key={agent.id} onClick={() => setSelectedKey(agent.agentKey)} className={`flex w-full items-start justify-between gap-4 rounded-xl border p-4 text-left transition-colors ${selectedKey === agent.agentKey ? "border-[#d5b400] bg-[#fff9d6]" : "border-border/60 hover:bg-muted/30"}`}><span><span className="flex flex-wrap items-center gap-2 font-medium"><Bot className="size-4 text-[#b58b00]" />{agent.name}<Badge variant={agent.status === "active" ? "default" : "outline"}>{statusLabel[agent.status] ?? agent.status}</Badge></span><span className="mt-1 block text-xs text-muted-foreground">{audienceLabel[agent.audience] ?? agent.audience} · autonomia {agent.autonomy} · {agent.agentKey}</span><span className="mt-1 block text-xs text-muted-foreground">Política {agent.policyVersion} · prompt {agent.promptVersion}</span></span><ShieldCheck className="size-4 shrink-0 text-emerald-600" /></button>) : <div className="rounded-xl bg-muted/40 p-5 text-sm text-muted-foreground">Nenhum agente cadastrado. Comece pelo perfil de operações.</div>}</CardContent></Card>

      <Card className="border-black/5 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-[#b58b00]" /> Novo perfil</CardTitle><CardDescription>Comece em A0/A1. O cadastro não libera execução automática por si só.</CardDescription></CardHeader><CardContent><form onSubmit={submitAgent} className="space-y-3"><div className="space-y-1"><Label>Chave</Label><Input value={form.agentKey} onChange={event => setForm({ ...form, agentKey: event.target.value })} /></div><div className="space-y-1"><Label>Nome</Label><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label>Público</Label><select value={form.audience} onChange={event => setForm({ ...form, audience: event.target.value })} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="admin">Administração</option><option value="partner">Parceiro</option><option value="consumer">Consumidor</option><option value="publisher">Divulgador</option><option value="internal">Interno</option></select></div><div className="space-y-1"><Label>Autonomia</Label><select value={form.autonomy} onChange={event => setForm({ ...form, autonomy: event.target.value })} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option>A0</option><option>A1</option><option>A2</option><option>A3</option><option>A4</option></select></div></div><Button type="submit" disabled={createAgent.isPending} className="w-full">{createAgent.isPending ? "Salvando…" : "Criar perfil"}</Button></form></CardContent></Card>
    </div>

    <Card className="border-black/5 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardCheck className="size-5 text-[#b58b00]" /> Planejar execução supervisionada</CardTitle><CardDescription>{activeAgent ? `Agente selecionado: ${activeAgent.name}. O resultado é idempotente e redige campos sensíveis.` : "Selecione um agente ativo para planejar uma execução."}</CardDescription></CardHeader><CardContent><form onSubmit={submitRun} className="grid gap-4 lg:grid-cols-[0.7fr_1fr_1.2fr] lg:items-end"><div className="space-y-1"><Label>Agente</Label><select value={selectedKey} onChange={event => setSelectedKey(event.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione</option>{(agents.data ?? []).filter(item => item.status === "active").map(item => <option key={item.id} value={item.agentKey}>{item.name}</option>)}</select></div><div className="space-y-1"><Label>Intenção</Label><select value={runForm.intent} onChange={event => setRunForm({ ...runForm, intent: event.target.value })} className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="consultar_cupom">Consultar cupom</option><option value="explicar_regra">Explicar regra</option><option value="simular_resgate">Simular resgate</option><option value="criar_rascunho">Criar rascunho</option><option value="publicar_oferta">Publicar oferta</option><option value="abrir_suporte">Abrir suporte</option></select></div><div className="space-y-1"><Label>Chave idempotente</Label><Input value={runForm.idempotencyKey} onChange={event => setRunForm({ ...runForm, idempotencyKey: event.target.value })} /></div><div className="space-y-1 lg:col-span-2"><Label>Contexto JSON redigível</Label><Textarea value={runForm.input} onChange={event => setRunForm({ ...runForm, input: event.target.value })} rows={3} /></div><div className="space-y-1"><Label>Referência</Label><Input value={runForm.requesterReference} onChange={event => setRunForm({ ...runForm, requesterReference: event.target.value })} /><Button type="submit" disabled={planRun.isPending || !activeAgent} className="mt-3 w-full"><CheckCircle2 className="mr-2 size-4" />{planRun.isPending ? "Planejando…" : "Planejar"}</Button></div></form></CardContent></Card>
  </main>;
}
