import { StatusBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { emptyToNull, formatDateTime } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Activity, CheckCircle2, ClipboardCheck, Plus, Search, SlidersHorizontal, TicketPercent } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type UseForm = { couponId: string; storeId: string; reference: string; customerReference: string; notes: string; usedAt: string };
const defaultForm: UseForm = { couponId: "", storeId: "", reference: "", customerReference: "", notes: "", usedAt: new Date().toISOString().slice(0, 16) };

export default function Uses() {
  const utils = trpc.useUtils();
  const [search, setSearch] = useState(""); const [partnerId, setPartnerId] = useState("all"); const [couponId, setCouponId] = useState("all"); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [dialogOpen, setDialogOpen] = useState(false); const [form, setForm] = useState<UseForm>(defaultForm);
  const partners = trpc.admin.partners.list.useQuery(undefined, { retry: false });
  const coupons = trpc.admin.coupons.list.useQuery(undefined, { retry: false });
  const selectedCoupon = availableCoupon(coupons.data, form.couponId);
  const storesInput = useMemo(() => selectedCoupon ? { partnerId: selectedCoupon.partnerId } : undefined, [selectedCoupon?.partnerId]);
  const stores = trpc.admin.stores.list.useQuery(storesInput, { retry: false });
  const filters = useMemo(() => ({ search: search || undefined, partnerId: partnerId === "all" ? undefined : Number(partnerId), couponId: couponId === "all" ? undefined : Number(couponId), startsAt: startsAt ? new Date(`${startsAt}T00:00:00`) : undefined, endsAt: endsAt ? new Date(`${endsAt}T23:59:59`) : undefined }), [search, partnerId, couponId, startsAt, endsAt]);
  const uses = trpc.admin.uses.list.useQuery(filters, { retry: false });
  const registerUse = trpc.admin.uses.register.useMutation({ onSuccess: async () => { await Promise.all([utils.admin.uses.list.invalidate(), utils.admin.coupons.list.invalidate(), utils.admin.dashboard.invalidate()]); toast.success("Utilização registrada com sucesso"); closeDialog(); }, onError: error => toast.error(error.message) });
  const availableCoupons = coupons.data?.filter(coupon => coupon.status === "active") ?? [];
  function closeDialog() { setDialogOpen(false); setForm(defaultForm); }
  function openDialog() { setForm({ ...defaultForm, couponId: availableCoupons[0]?.id?.toString() ?? "" }); setDialogOpen(true); }
  function saveUse() { const payload = { couponId: Number(form.couponId), storeId: form.storeId ? Number(form.storeId) : null, reference: form.reference.trim(), customerReference: emptyToNull(form.customerReference), notes: emptyToNull(form.notes), usedAt: new Date(form.usedAt) }; if (!payload.couponId || !payload.reference || !payload.customerReference || Number.isNaN(payload.usedAt.getTime())) return toast.error("Selecione o cupom e informe a referência do cliente e da utilização"); registerUse.mutate(payload); }
  return <div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-primary-foreground/60">Acompanhamento</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Utilizações</h1><p className="mt-2 text-sm text-muted-foreground">Registre cada uso e mantenha o saldo dos benefícios sob acompanhamento.</p></div><Button onClick={openDialog} className="h-11 gap-2 px-5 font-bold"><Plus className="h-4 w-4" /> Registrar uso</Button></header>
    <section className="grid gap-3 rounded-2xl border border-black/5 bg-white p-4 shadow-[0_6px_20px_rgba(17,20,24,0.025)] md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_180px_180px_150px_150px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={event => setSearch(event.target.value)} className="h-10 border-black/7 bg-[#fafaf7] pl-9" placeholder="Buscar referência ou cupom" /></div><Select value={partnerId} onValueChange={setPartnerId}><SelectTrigger className="h-10 border-black/7 bg-[#fafaf7]"><SelectValue placeholder="Parceiro" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os parceiros</SelectItem>{partners.data?.map(partner => <SelectItem key={partner.id} value={partner.id.toString()}>{partner.displayName}</SelectItem>)}</SelectContent></Select><Select value={couponId} onValueChange={setCouponId}><SelectTrigger className="h-10 border-black/7 bg-[#fafaf7]"><SelectValue placeholder="Cupom" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os cupons</SelectItem>{coupons.data?.map(coupon => <SelectItem key={coupon.id} value={coupon.id.toString()}>{coupon.code}</SelectItem>)}</SelectContent></Select><Input type="date" value={startsAt} onChange={event => setStartsAt(event.target.value)} className="h-10 border-black/7 bg-[#fafaf7]" aria-label="Data inicial" /><Input type="date" value={endsAt} onChange={event => setEndsAt(event.target.value)} className="h-10 border-black/7 bg-[#fafaf7]" aria-label="Data final" /></section>
    <section className="overflow-hidden rounded-[1.5rem] border border-black/5 bg-white shadow-[0_8px_26px_rgba(17,20,24,0.035)]"><div className="hidden grid-cols-[1.1fr_1.05fr_1fr_1fr_120px] gap-4 border-b border-black/5 px-6 py-3 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground lg:grid"><span>Referência</span><span>Cupom</span><span>Parceiro</span><span>Cliente / observação</span><span>Data</span></div>{uses.isLoading && <div className="p-8 text-sm text-muted-foreground">Carregando utilizações…</div>}{uses.isError && <div className="p-8 text-sm text-rose-700">Não foi possível carregar as utilizações. Tente novamente.</div>}{!uses.isLoading && !uses.isError && uses.data?.length === 0 && <EmptyUses onRegister={openDialog} />}<div className="divide-y divide-black/5">{uses.data?.map(use => <div key={use.id} className="grid gap-4 px-5 py-5 lg:grid-cols-[1.1fr_1.05fr_1fr_1fr_120px] lg:items-center lg:px-6"><div className="flex items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><CheckCircle2 className="h-4 w-4" /></div><div><p className="text-sm font-extrabold">{use.reference}</p><StatusBadge status="active" label="Confirmado" /></div></div><div><p className="text-sm font-extrabold">{use.couponCode}</p><p className="text-xs text-muted-foreground">{use.couponTitle}</p></div><div><p className="text-xs font-bold">{use.partnerName}</p><p className="mt-1 text-[11px] text-primary-foreground">{use.storeName || "Todas as lojas"}</p></div><div className="min-w-0"><p className="truncate text-xs">{use.customerReference || "Cliente não identificado"}</p><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{use.notes || "Sem observações"}</p></div><p className="text-xs font-medium text-muted-foreground">{formatDateTime(use.usedAt)}</p></div>)}</div></section>
    <Dialog open={dialogOpen} onOpenChange={open => !open && closeDialog()}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Registrar utilização</DialogTitle><DialogDescription>O saldo do cupom será atualizado após a confirmação deste registro.</DialogDescription></DialogHeader><div className="grid gap-5 py-3"><Field label="Cupom ativo *"><Select value={form.couponId} onValueChange={value => setForm({ ...form, couponId: value, storeId: "" })}><SelectTrigger><SelectValue placeholder="Selecione o cupom" /></SelectTrigger><SelectContent>{availableCoupons.map(coupon => <SelectItem key={coupon.id} value={coupon.id.toString()}>{coupon.code} · {coupon.partnerName}</SelectItem>)}</SelectContent></Select></Field><Field label="Loja do resgate"><Select value={form.storeId || "none"} onValueChange={value => setForm({ ...form, storeId: value === "none" ? "" : value })}><SelectTrigger><SelectValue placeholder="Todas as lojas" /></SelectTrigger><SelectContent><SelectItem value="none">Aplicável a todas as lojas</SelectItem>{stores.data?.map(({ store }) => <SelectItem key={store.id} value={store.id.toString()}>{store.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Referência operacional *"><Input value={form.reference} onChange={event => setForm({ ...form, reference: event.target.value })} placeholder="Ex.: PED-2026-0001" /><p className="text-[11px] text-muted-foreground">Identifica esta transação; não é o identificador do cliente.</p></Field><Field label="Data e hora do uso *"><Input type="datetime-local" value={form.usedAt} onChange={event => setForm({ ...form, usedAt: event.target.value })} /></Field><Field label="Referência do cliente pseudonimizado *"><Input value={form.customerReference} onChange={event => setForm({ ...form, customerReference: event.target.value })} placeholder="Ex.: user-demo-001" /><p className="text-[11px] text-muted-foreground">Preencha o identificador do cliente aqui; ele é separado da referência operacional e aplica limites individuais.</p></Field><Field label="Observações"><Textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} className="min-h-24 resize-none" placeholder="Informações adicionais do resgate" /></Field></div><DialogFooter><Button variant="outline" onClick={closeDialog}>Cancelar</Button><Button onClick={saveUse} disabled={registerUse.isPending}>{registerUse.isPending ? "Registrando…" : "Confirmar uso"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function availableCoupon(coupons: Array<{ id: number; partnerId: number; status: string }> | undefined, id: string) { return coupons?.find(coupon => coupon.id.toString() === id && coupon.status === "active"); }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-xs font-bold">{label}</Label>{children}</div>; }
function EmptyUses({ onRegister }: { onRegister: () => void }) { return <div className="px-6 py-16 text-center"><ClipboardCheck className="mx-auto h-7 w-7 text-primary" /><h2 className="mt-4 text-base font-extrabold">Nenhuma utilização encontrada.</h2><p className="mt-1 text-sm text-muted-foreground">Quando um cupom for usado, o registro aparecerá nesta linha do tempo.</p><Button variant="outline" onClick={onRegister} className="mt-5 gap-2"><Plus className="h-4 w-4" /> Registrar primeira utilização</Button></div>; }
